version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - API_PORT=8000
      - CORS_ORIGINS=http://localhost:5174

  frontend:
    build: ./frontend
    ports:
      - "5174:80"
    environment:
      - VITE_API_BASE=http://localhost:8000
    depends_on:
      - api